travis:
  secure:
    BINSTAR_TOKEN: jsPWMf9hxY6wdqmvVvpk6gL7viWwaK+Mn7V2xZvpE+WpVa7NJpbJFc/2yJYlYiRmiAGseBIp9+aj0ZwgoQxGiHkSPNqJU9Ev/TtDZekmISanW7TJehKtQ1IJdKGJj8ZElVpg5y/+xdw0791Beo/fMgue5xLgtSvVu8U9isr9EUEmzDdtl+Iaho+P5ezzD6Lza++1Ad5zAuM8ydjj9KLIv9xw23kaU+y2x17S6d9ZpXGbe5tJGpac7sDttRhTxNpvcv6gU3GA9jWBuodBVrPYBdfgr3aVLxB/HlRbbxGJrZySw1FnVdupGaRdH1EgittMvosnmF+YUoWRpRzOPxcXu7iTM0pZLg3gsaUmk2BD5U83OG1alpta/pH1FyduvwPXlHJX1P4qbMuSSQnY3RKz+SJUa2GdnrdNYDr2I8SFkhJ8jQup9AZougv6JC6LL6njTqpRuYm9OI5ixlzHBFZj4aoOUHS6voF76BSTYf9IYExBSCE1ljfQoh/A8htEzZHd7WKCRD7nGPaApeF6anQviEAqI8yqb4Up9CzJtpUpf0K6IOSB8ngXIG6mDmWkG6IdWrNjco6s+7Or/lqVilzusRlzkyyViJ10ipvT0wQ81pz6ihDFCloEqORMK8myhQtZrdb2ssC7hgPCm9zGF1pQI+iscV5U1qEmAvodT1hZTJs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
