travis:
  secure:
    BINSTAR_TOKEN: YT6cqW3KpaeZmhtaVQkWVpX1i4Gw5QbwlevR9xy7mwG5+yGZ67tk4LuhxkmxCoC9sN7624gKctJhRzgPoqz9GdAQm2GouaXILNakSxjf5GwnRb74IL5Tw3POs+MJsugoMVnlIA01d9vsK7nkCx86uGxONCSRla3KRKIRdzP31du4RFiLoYEurNsmgp4muKGUUxnlwoveRFxwOnF6FvokMVGNU5cFzSYKE/pgzIGgfVEaTXbLJijM0klvcZzr0j9BLwscn1pUrAyKixFOMr/nTeYFqtYxH+iq2IyzRk+cZeyG7Y0T0MSq0c3Jmw5AQ5p3Z2OhaY2mRO+MTjQlac+sdU5VFBvIekVx3iOG50NoVstUNQw7LQfFx6tX0gbI0oXKQmZ9FNknv/oQ1KV3dhBLDb1Txo8K1PtYKN7JcPF8YDOMHnb5xtJdNLf3El9cboLElOK9uGwI6PUflN85uBqzCsUpILycxYfNe9XWZABR2FtUZZ94nHtI9Udhqbougfh1aFIgyGGeNX8XcpEo2gEvEWrrOD3BTc2KLecwZAT/OUsagFQVPQ1+4d851eV8LhtoPwFrwaTPPj7omHBcKV0xOX7addLD7OzWgLPoiD51RkxPmhtT58nZrlqW0vLF5dzPEnHKn8lb3xtGTqsQCT7dvVeeJX8mr9jQkFxcAgztAro=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
